### ISSUE TITLE
Have a look at the numeric range that this function outputs. Is it compatible with the comparison done using 1-hot encoded vectors?

### ISSUE THREAD

**Issue by spalaciob** [00SteinsGate00/Cifar-10-Image-Classifcation-using-LeNet5#1]
https://github.com/00SteinsGate00/Cifar-10-Image-Classifcation-using-LeNet5/blob/bf838b212b5351c035c2c13f34a35c3a12fe3150/cifar10_classification.py#L35

**Comment by j-holub** [comment]
True, I didn't really think about that. I'm trying out **Softmax** since it's similar to the **Sigmoid** function but is supposed to work better in most cases for classification.
